export const mockMortgageProduct = {
  bestRate: 1.25,
  created: '2021-06-07T13:30:38Z',
  family: 'VALUE_FLEX',
  fixedPenaltySpread: 'SMALL_PENALTY',
  helocDelta: 0,
  helocOption: 'HELOC_WITHOUT',
  id: 12345,
  insurable: true,
  insurance: 'CONVENTIONAL',
  lenderName: 'nesto',
  lenderType: 'MONOLINE',
  name: 'MCAP Value-Flex Variable Special',
  prepaymentOption: 'STANDARD',
  rate: 1.45,
  rateHold: '120_DAYS',
  ratePrimeVariance: -1.2,
  restrictions: 'MCAP_VALUE_FLEX_RESTRICTIONS',
  restrictionsOption: 'SOME_RESTRICTIONS',
  term: '5_YEAR',
  type: 'VARIABLE',
  updated: '2021-06-07T13:47:09Z',
};
